// BatchUploadPanel — the batch verification flow: two labeled upload zones (a CSV
// manifest zone with a downloadable template, and a plain multi-file image picker),
// a preflight pairing summary the user must explicitly confirm before anything is
// uploaded, then a chunked server-driven processing loop with visible progress,
// single-active-tab lock handling, and a resume prompt for a batch left unfinished by
// a previous page load. All the pairing/verification logic this component drives
// already exists elsewhere (the CSV parser, the Blob upload helper, the batch API
// routes) — this file's own job is orchestrating the client-side sequence those pieces
// were each built to support: parse -> confirm -> upload -> register -> process-loop.
//
// Client-side "batch id" versus server-assigned "batch id": uploading a label image
// needs a batch id up front, to namespace where in Blob storage it's stored, but the
// only batch id that will ever really mean anything (the one every later
// /api/batch/[id]/process call is keyed on) is generated by the server, inside the
// batch-registration route, only *after* every image has already finished uploading.
// This component resolves that ordering by generating its own random id purely to
// namespace this one batch's uploads in Blob storage, then discarding it the moment
// registration hands back the real one — the two ids are never expected to match, and
// nothing downstream of registration ever looks at the client-generated one again.

"use client";

import { useEffect, useMemo, useRef, useState, type ChangeEvent } from "react";
import { csvManifestParser } from "@/lib/batchInput/csvManifestParser";
import type { BatchEntry, PairingError } from "@/lib/batchInput/types";
import { resultsToCsv } from "@/lib/export/resultsToCsv";
import { getOrCreateTabId } from "@/lib/persistence/batchLock";
import { uploadLabelImage } from "@/lib/persistence/blobUpload";
import type { BatchRowState } from "@/lib/persistence/kvStore";
import ResultsTable from "./ResultsTable";
import { KNOWN_FIELDS } from "./UploadForm";
import styles from "./BatchUploadPanel.module.css";

/**
 * How long one label is estimated to take to verify, in milliseconds, used only to
 * turn a pending-row count into a human "about N minutes remaining" estimate for the
 * progress display. Matches the real, measured per-call latency this app's extraction
 * provider was clocked at on real label images (a couple of seconds each) plus a
 * little overhead for the surrounding request — not a guess pulled from nowhere, and
 * consistent with why a 200-300 label batch is disclosed as taking on the order of
 * twenty minutes rather than being implied to be instant.
 */
const ESTIMATED_MS_PER_LABEL = 4_000;

/** Filename offered for the downloadable CSV template. */
const CSV_TEMPLATE_FILE_NAME = "label-batch-template.csv";

/** Filename offered for the downloadable results CSV. */
const RESULTS_CSV_FILE_NAME = "label-batch-results.csv";

/**
 * Escapes one CSV field per the same RFC4180 quoting rule the manifest parser itself
 * expects to read back: wrap in double quotes, and double any literal quote character,
 * whenever the field contains a comma, a quote, or a newline that would otherwise be
 * misread as a field or row boundary. Exported (like every pure helper in this file)
 * so it's directly unit-testable without rendering any React component.
 */
export function csvEscape(value: string): string {
  if (/[",\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

/**
 * Builds the downloadable CSV template's full text: a header row (the two reserved
 * pairing/bookkeeping columns, `fileName` and `id`, followed by every field the
 * single-verify form already has a dedicated input for) plus one filled-in example
 * row, so the format is discoverable by looking at it rather than needing separate
 * documentation. Reuses UploadForm's own KNOWN_FIELDS list (both its column keys and
 * its example placeholder text) as the single source of truth for what these fields
 * are called and look like, rather than maintaining a second, parallel list here that
 * could quietly drift out of sync with the single-verify form. One field's placeholder
 * text (`countryOfOrigin`) is instructional prose meant for an empty form input, not
 * realistic example data, so the template's example row leaves that one cell blank
 * instead — which doubles as a working example of "a field the application simply
 * doesn't have," since a blank CSV cell is exactly how this app already represents that.
 */
export function buildCsvTemplate(): string {
  const header = ["fileName", "id", ...KNOWN_FIELDS.map((field) => field.key)];
  const exampleRow = [
    "IMG_001.jpg",
    "1042",
    ...KNOWN_FIELDS.map((field) => (field.key === "countryOfOrigin" ? "" : field.placeholder)),
  ];
  return [header, exampleRow].map((row) => row.map(csvEscape).join(",")).join("\r\n") + "\r\n";
}

/** The counts a preflight pairing summary needs to render — how many rows are ready to
 * go, and the two ways a row or an uploaded image can fail to find its counterpart. */
export type PreflightSummary = {
  matchedCount: number;
  /** Matched rows plus rows whose named image never showed up — i.e. every CSV row
   * that was actually trying to pair with an image, the denominator for a "298/300
   * matched" style count (an extra, unclaimed image isn't counted here, since it was
   * never a CSV row in the first place). */
  totalCsvRowsConsidered: number;
  noMatchingImageErrors: PairingError[];
  noMatchingRowErrors: PairingError[];
};

/**
 * Reshapes a BatchInputParser's raw `entries`/`errors` output into the counts a
 * preflight summary displays, splitting `errors` by its two possible reasons so the
 * UI can report each direction of mismatch separately ("2 rows have no image" versus
 * "1 image has no row"), matching the two distinct situations PairingError's own doc
 * comment describes. Pure and synchronous — no parsing happens here, only counting —
 * so it's directly unit-testable against hand-built entries/errors fixtures.
 */
export function buildPreflightSummary(entries: BatchEntry[], errors: PairingError[]): PreflightSummary {
  const noMatchingImageErrors = errors.filter((error) => error.reason === "no_matching_image");
  const noMatchingRowErrors = errors.filter((error) => error.reason === "no_matching_row");
  return {
    matchedCount: entries.length,
    totalCsvRowsConsidered: entries.length + noMatchingImageErrors.length,
    noMatchingImageErrors,
    noMatchingRowErrors,
  };
}

/**
 * Turns one PairingError into a human-readable sentence for the preflight summary's
 * detail list, phrased differently depending on which side of the mismatch it is
 * (a CSV row with nothing to pair to it, versus an uploaded image nothing claimed) so
 * the user can tell at a glance which file needs attention and why.
 */
export function describePairingError(error: PairingError): string {
  return error.reason === "no_matching_image"
    ? `"${error.fileName}" is listed in the CSV manifest, but no uploaded image has that exact filename.`
    : `An image named "${error.fileName}" was uploaded, but no CSV row lists that exact filename.`;
}

/**
 * Turns a still-pending row count into a human "about N minutes remaining" sentence,
 * so the batch progress view discloses roughly how long a run will take rather than
 * leaving the wait unexplained — a full 200-300 label batch is a genuinely multi-minute
 * process at this app's extraction provider's rate limit, not something that should
 * ever read as stalled or instant.
 */
export function formatEstimatedTimeRemaining(pendingCount: number, msPerLabel: number = ESTIMATED_MS_PER_LABEL): string {
  if (pendingCount <= 0) {
    return "Done.";
  }
  const totalMinutes = Math.ceil((pendingCount * msPerLabel) / 60_000);
  if (totalMinutes <= 1) {
    return "About a minute remaining.";
  }
  return `About ${totalMinutes} minutes remaining.`;
}

/**
 * Overlays one round's freshly-processed rows onto a full row list, replacing each row
 * whose fileName matches and leaving every other row exactly as it was — how this
 * component folds each `/api/batch/[id]/process` response into its own local copy of
 * batch progress without re-fetching every row from the server on every call. Pure and
 * synchronous, mirroring the same overlay the server route itself performs internally
 * for its own response shaping.
 */
export function applyProcessedRows(rows: BatchRowState[], processedRows: BatchRowState[]): BatchRowState[] {
  if (processedRows.length === 0) {
    return rows;
  }
  const processedByFileName = new Map(processedRows.map((row) => [row.fileName, row]));
  return rows.map((row) => processedByFileName.get(row.fileName) ?? row);
}

/** Everything GET /api/batch/current reports for a batch worth offering to resume. */
type ResumableBatch = {
  batchId: string;
  totalCount: number;
  doneCount: number;
  pendingCount: number;
  isComplete: boolean;
  rows: BatchRowState[];
};

/** Everything one round of POST /api/batch/[id]/process reports back. */
type ProcessRoundResult = {
  batchId: string;
  totalCount: number;
  doneCount: number;
  pendingCount: number;
  isComplete: boolean;
  processedRows: BatchRowState[];
  rowErrors: { fileName: string; error: string }[];
};

/**
 * The coarse stage this whole panel is in. A handful of narrower flags (e.g. which
 * general error message is showing, or whether an unfinished batch was found to offer
 * resuming) live alongside this in separate state, but this value is what decides which
 * whole block of UI renders — upload zones, or the live progress view. There is
 * deliberately no separate "checking for a resumable batch" phase that gates the setup
 * screen behind a loading state: the upload zones render immediately (matching what
 * gets prerendered at build time), and the resume-check runs in the background,
 * surfacing a banner above the zones if it finds something worth offering — a page load
 * is never left staring at a bare "checking…" message before it can do anything.
 */
type Phase = "setup" | "uploading" | "processing" | "processingPaused" | "lockBlocked" | "complete";

/**
 * The resume-prompt banner shown above the upload zones when a page load finds an
 * unfinished batch already registered for this browser. Offers exactly two explicit
 * choices — continue the existing batch, or dismiss this banner and start a fresh
 * one — never auto-resumes without the user seeing this first, per this app's own
 * "nothing proceeds without an explicit confirmation" rule for the batch flow. Shown
 * alongside the ordinary upload zones, not instead of them, so a user who'd rather
 * ignore an old batch and start over isn't blocked from doing exactly that.
 */
function ResumeBanner({
  batch,
  onResume,
  onStartFresh,
}: {
  batch: ResumableBatch;
  onResume: () => void;
  onStartFresh: () => void;
}) {
  return (
    <div className={styles.resumeBanner}>
      <p>
        You have an unfinished batch: <strong>{batch.doneCount}</strong> of{" "}
        <strong>{batch.totalCount}</strong> labels already verified.
      </p>
      <div className={styles.resumeActions}>
        <button type="button" className={styles.primaryButton} onClick={onResume}>
          Resume this batch
        </button>
        <button type="button" className={styles.secondaryButton} onClick={onStartFresh}>
          Start a new batch instead
        </button>
      </div>
    </div>
  );
}

/**
 * The detail list under a preflight summary's headline counts, one line per unpaired
 * row or image — rendered only when at least one exists, since a perfectly-paired
 * manifest has nothing to list here.
 */
function PairingErrorList({ errors }: { errors: PairingError[] }) {
  if (errors.length === 0) {
    return null;
  }
  return (
    <ul className={styles.pairingErrorList}>
      {errors.map((error) => (
        <li key={`${error.reason}:${error.fileName}`}>{describePairingError(error)}</li>
      ))}
    </ul>
  );
}

/**
 * One row's own line in the live progress view: a finished row reuses ResultsTable
 * (the same expandable field-by-field comparison single-verify already shows) rather
 * than a second, parallel rendering of the same FieldResult data, so a batch result and
 * a single-verify result always look identical. A still-pending or in-flight row gets a
 * plain status line instead, since there's nothing to compare yet.
 *
 * `elapsedSeconds` is the measured wall-clock time of whichever `/process` call this
 * row actually finished on, when this browser tab is the one that ran it — several rows
 * can share one such measurement, since up to N of them finish together within the same
 * call. A row that was already "done" before this tab ever started polling (re-hydrated
 * from a resumed batch) has no such measurement available, and falls back to 0 rather
 * than a fabricated number.
 */
function BatchRowItem({ row, elapsedSeconds }: { row: BatchRowState; elapsedSeconds?: number }) {
  if (row.status === "done" && row.result) {
    return (
      <li className={styles.doneRow}>
        <ResultsTable result={row.result} elapsedSeconds={elapsedSeconds ?? 0} />
      </li>
    );
  }
  return (
    <li className={styles.pendingRow}>
      <span className={styles.pendingFileName}>{row.fileName}</span>
      <span className={styles.pendingStatus}>{row.status === "in_flight" ? "Verifying…" : "Waiting…"}</span>
    </li>
  );
}

/**
 * BatchUploadPanel — the top-level export. Owns every piece of state the batch flow
 * needs end to end: which coarse Phase it's in, the CSV/image selections and their
 * client-side preflight pairing result, the registered batch's id and every row's
 * latest known state, and whatever error/lock message currently needs showing. See
 * this file's own header comment for the overall parse -> confirm -> upload ->
 * register -> process-loop sequence this component drives.
 */
export default function BatchUploadPanel() {
  const [phase, setPhase] = useState<Phase>("setup");
  const [resumeCandidate, setResumeCandidate] = useState<ResumableBatch | null>(null);

  const [csvText, setCsvText] = useState<string | null>(null);
  const [csvFileName, setCsvFileName] = useState<string | null>(null);
  const [imageFiles, setImageFiles] = useState<File[]>([]);

  const [batchId, setBatchId] = useState<string | null>(null);
  const [totalCount, setTotalCount] = useState(0);
  const [rows, setRows] = useState<BatchRowState[]>([]);
  const [rowElapsedSeconds, setRowElapsedSeconds] = useState<Record<string, number>>({});
  const [recentRowErrors, setRecentRowErrors] = useState<{ fileName: string; error: string }[]>([]);

  const [generalError, setGeneralError] = useState<string | null>(null);
  const [lockHolderTabId, setLockHolderTabId] = useState<string | null>(null);

  // Guards the processing loop against continuing to call setState (or, worse, keep
  // looping forever) once this component has unmounted — e.g. the user navigated away
  // from the batch tab mid-run. A ref, not state, since flipping it must never itself
  // trigger a re-render; it only needs to be readable from inside the loop's own
  // already-running async function.
  const stopLoopRef = useRef(false);

  useEffect(() => {
    stopLoopRef.current = false;
    void checkForResumableBatch();
    return () => {
      stopLoopRef.current = true;
    };
    // Deliberately runs once on mount only — checkForResumableBatch is stable (defined
    // fresh each render but closes over no state that would need re-running this effect).
  }, []);

  /**
   * On mount, asks the server whether this browser already has an unfinished batch
   * registered (GET /api/batch/current relies entirely on the browser's own cookie —
   * no request body needed). This runs in the background against the upload zones,
   * which are already visible the moment this component mounts — a found, genuinely
   * unfinished batch adds a resume banner above them; a found-and-already-complete
   * batch has nothing left to resume, so it's treated the same as "nothing found" here;
   * any failure of this check (e.g. a network hiccup) is likewise treated as "nothing
   * found" rather than surfaced as an error, since a resume offer is a convenience on
   * top of the plain upload flow, not something that flow depends on.
   */
  async function checkForResumableBatch() {
    try {
      const response = await fetch("/api/batch/current");
      const body = (await response.json()) as { batch: ResumableBatch | null };
      if (body.batch && !body.batch.isComplete) {
        setResumeCandidate(body.batch);
      }
    } catch {
      // Nothing to do — the upload zones are already usable without this check.
    }
  }

  function handleResume() {
    if (!resumeCandidate) {
      return;
    }
    setBatchId(resumeCandidate.batchId);
    setTotalCount(resumeCandidate.totalCount);
    setRows(resumeCandidate.rows);
    setResumeCandidate(null);
    setPhase("processing");
    void runProcessingLoop(resumeCandidate.batchId);
  }

  /** Dismisses the resume banner without touching the upload zones underneath it,
   * which were already visible and usable the whole time. */
  function handleStartFresh() {
    setResumeCandidate(null);
  }

  function handleCsvFileChange(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0] ?? null;
    setCsvFileName(file?.name ?? null);
    setGeneralError(null);
    if (!file) {
      setCsvText(null);
      return;
    }
    // FileReader, not file.text(), so this keeps working the same way on every browser
    // this app targets without depending on the newer File.text() promise API.
    const reader = new FileReader();
    reader.onload = () => setCsvText(typeof reader.result === "string" ? reader.result : null);
    reader.onerror = () => setGeneralError("Could not read the selected CSV file. Please try selecting it again.");
    reader.readAsText(file);
  }

  function handleImageFilesChange(event: ChangeEvent<HTMLInputElement>) {
    setImageFiles(event.target.files ? Array.from(event.target.files) : []);
  }

  function handleDownloadCsvTemplate() {
    const blob = new Blob([buildCsvTemplate()], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = CSV_TEMPLATE_FILE_NAME;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Downloads the batch's results so far as a CSV file, via resultsToCsv() — reuses
   * exactly the same Blob-plus-temporary-<a>-click download pattern
   * handleDownloadCsvTemplate() above already uses for the manifest template, since
   * both are the same kind of client-side, no-server-round-trip file download.
   * Deliberately callable at any point once at least one row has finished (not gated
   * behind the whole batch being complete): resultsToCsv() already skips any row that
   * hasn't finished yet, so a download mid-batch simply reports whatever's been
   * verified so far, which is still useful to a user who doesn't want to wait for the
   * full ~20-minute run before seeing anything.
   */
  function handleDownloadResults() {
    const blob = new Blob([resultsToCsv(rows)], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = RESULTS_CSV_FILE_NAME;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  // Recomputed only when the CSV text or the image file list actually changes, not on
  // every render — parsing/pairing a few hundred rows on each keystroke elsewhere in
  // this component would be wasted work. `null` means "not enough has been provided
  // yet to attempt pairing"; once both a CSV and at least one image are present, this
  // either holds a successful parse or the error csvManifestParser.parse() throws for a
  // structurally broken manifest (e.g. no fileName column at all).
  const parseAttempt = useMemo(() => {
    if (!csvText || imageFiles.length === 0) {
      return null;
    }
    try {
      return { ok: true as const, result: csvManifestParser.parse(csvText, imageFiles) };
    } catch (error) {
      return {
        ok: false as const,
        message: error instanceof Error ? error.message : "Could not parse the CSV manifest.",
      };
    }
  }, [csvText, imageFiles]);

  const preflightSummary =
    parseAttempt?.ok ? buildPreflightSummary(parseAttempt.result.entries, parseAttempt.result.errors) : null;

  /**
   * The user's explicit "Proceed with N matched" confirmation — the one moment this
   * whole flow is allowed to start actually uploading anything. Uploads every matched
   * entry's image directly to Blob (bypassing this app's own API routes for the image
   * bytes themselves, the same reasoning app/api/verify/route.ts never needed to when
   * it only ever handles one image), registers the resulting rows as a new batch, then
   * hands off to the processing loop. Any failure at any step here (an upload, or the
   * registration call itself) surfaces as a general error and returns the user to the
   * setup screen rather than leaving the panel stuck mid-way with no way forward.
   */
  async function confirmAndStart(entries: BatchEntry[]) {
    setPhase("uploading");
    setGeneralError(null);
    try {
      // Purely a Blob-storage namespace for this one upload pass — see this file's own
      // header comment for why this never needs to match the batchId the registration
      // call below actually assigns.
      const uploadNamespaceId = crypto.randomUUID();
      const uploadedRows = await Promise.all(
        entries.map(async (entry) => {
          const { blobRef } = await uploadLabelImage(entry.image, {
            batchId: uploadNamespaceId,
            fileName: entry.fileName,
          });
          return { id: entry.id, fileName: entry.fileName, applicationData: entry.applicationData, blobRef };
        })
      );

      const registerResponse = await fetch("/api/batch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ rows: uploadedRows }),
      });
      if (!registerResponse.ok) {
        const body = (await registerResponse.json().catch(() => null)) as { error?: string } | null;
        throw new Error(body?.error ?? `Failed to register the batch (HTTP ${registerResponse.status}).`);
      }
      const { batchId: newBatchId, totalCount: newTotalCount } = (await registerResponse.json()) as {
        batchId: string;
        totalCount: number;
      };

      const initialRows: BatchRowState[] = uploadedRows.map((row) => ({ ...row, status: "pending" }));
      setBatchId(newBatchId);
      setTotalCount(newTotalCount);
      setRows(initialRows);
      setPhase("processing");
      void runProcessingLoop(newBatchId);
    } catch (error) {
      setGeneralError(error instanceof Error ? error.message : "Failed to start the batch. Please try again.");
      setPhase("setup");
    }
  }

  /**
   * The chunked processing loop: repeatedly calls POST /api/batch/[id]/process, one
   * call after another, for as long as this tab stays open, this component stays
   * mounted, and the server keeps reporting the batch isn't complete yet. There's no
   * artificial delay inserted between calls — each call's own round trip (a real
   * network request plus however long the extraction call inside it takes) already
   * paces successive calls at roughly the extraction provider's own rate-limit ceiling,
   * so adding a client-side delay on top would only slow the batch down further, not
   * make it safer.
   *
   * Stops outright (rather than retrying) on the two conditions the plan explicitly
   * calls for: a 409 (another tab holds the lock) shows a clear message instead of
   * racing that other tab, and any other failed call surfaces an error with a manual
   * "Resume Processing" button rather than looping tightly against a server that just
   * failed. A row-level failure inside an otherwise-successful call is different — the
   * server already leaves that row safely retryable on its own next attempt, so this
   * loop simply keeps going rather than treating one bad row as a reason to stop.
   */
  async function runProcessingLoop(activeBatchId: string) {
    const tabId = getOrCreateTabId();

    while (!stopLoopRef.current) {
      const startedAt = performance.now();
      let response: Response;
      try {
        response = await fetch(`/api/batch/${activeBatchId}/process`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ tabId }),
        });
      } catch {
        if (!stopLoopRef.current) {
          setGeneralError("Lost connection while processing the batch.");
          setPhase("processingPaused");
        }
        return;
      }
      const elapsedSeconds = (performance.now() - startedAt) / 1000;
      if (stopLoopRef.current) {
        return;
      }

      if (response.status === 409) {
        const body = (await response.json().catch(() => null)) as { heldByAnotherTabId?: string } | null;
        setLockHolderTabId(body?.heldByAnotherTabId ?? null);
        setPhase("lockBlocked");
        return;
      }
      if (!response.ok) {
        const body = (await response.json().catch(() => null)) as { error?: string } | null;
        setGeneralError(body?.error ?? `Batch processing failed (HTTP ${response.status}).`);
        setPhase("processingPaused");
        return;
      }

      const round = (await response.json()) as ProcessRoundResult;
      setTotalCount(round.totalCount);
      setRows((previous) => applyProcessedRows(previous, round.processedRows));
      setRecentRowErrors(round.rowErrors);
      if (round.processedRows.length > 0) {
        setRowElapsedSeconds((previous) => {
          const next = { ...previous };
          for (const processedRow of round.processedRows) {
            next[processedRow.fileName] = elapsedSeconds;
          }
          return next;
        });
      }

      if (round.isComplete) {
        setPhase("complete");
        return;
      }
      // Otherwise: loop immediately to the next call, still processing.
    }
  }

  function handleResumeProcessingAfterPause() {
    if (!batchId) {
      return;
    }
    setGeneralError(null);
    setPhase("processing");
    void runProcessingLoop(batchId);
  }

  function handleStartOver() {
    setPhase("setup");
    setResumeCandidate(null);
    setCsvText(null);
    setCsvFileName(null);
    setImageFiles([]);
    setBatchId(null);
    setTotalCount(0);
    setRows([]);
    setRowElapsedSeconds({});
    setRecentRowErrors([]);
    setGeneralError(null);
    setLockHolderTabId(null);
  }

  const doneCount = rows.filter((row) => row.status === "done").length;
  const pendingCount = totalCount - doneCount;

  return (
    <section className={styles.panel} aria-labelledby="batch-heading">
      <h2 id="batch-heading">Batch Verification</h2>
      <p className={styles.intro}>
        Verify many labels at once: a CSV manifest of application data, paired with the
        label images it names, checked one by one. A full 200-300 label batch takes on
        the order of twenty minutes to finish — progress is saved as it goes, so leaving
        and returning to this page later picks up right where it left off.
      </p>

      {phase === "setup" && resumeCandidate && (
        <ResumeBanner batch={resumeCandidate} onResume={handleResume} onStartFresh={handleStartFresh} />
      )}

      {phase === "setup" && (
        <>
          <div className={styles.uploadZones}>
            <div className={styles.zone}>
              <h3>1. CSV Manifest</h3>
              <p>
                One row per label, with a <code>fileName</code> column naming its image
                exactly.{" "}
                <button type="button" className={styles.linkButton} onClick={handleDownloadCsvTemplate}>
                  Download CSV template
                </button>
              </p>
              <input id="batch-csv" type="file" accept=".csv,text/csv" onChange={handleCsvFileChange} />
              {csvFileName && <p className={styles.selectedFile}>Selected: {csvFileName}</p>}
            </div>

            <div className={styles.zone}>
              <h3>2. Label Images</h3>
              <p>Select every label image the CSV manifest refers to, all at once.</p>
              <input
                id="batch-images"
                type="file"
                accept="image/*"
                multiple
                onChange={handleImageFilesChange}
              />
              {imageFiles.length > 0 && (
                <p className={styles.selectedFile}>
                  Selected: {imageFiles.length} image{imageFiles.length === 1 ? "" : "s"}
                </p>
              )}
            </div>
          </div>

          {generalError && (
            <div className={styles.errorBadge} role="alert">
              {generalError}
            </div>
          )}

          {parseAttempt && !parseAttempt.ok && (
            <div className={styles.errorBadge} role="alert">
              {parseAttempt.message}
            </div>
          )}

          {preflightSummary && (
            <div className={styles.preflight}>
              <p className={styles.preflightHeadline}>
                <strong>
                  {preflightSummary.matchedCount}/{preflightSummary.totalCsvRowsConsidered}
                </strong>{" "}
                rows matched an image.
                {preflightSummary.noMatchingImageErrors.length > 0 &&
                  ` ${preflightSummary.noMatchingImageErrors.length} row(s) have no image.`}
                {preflightSummary.noMatchingRowErrors.length > 0 &&
                  ` ${preflightSummary.noMatchingRowErrors.length} image(s) have no row.`}
              </p>
              <PairingErrorList errors={preflightSummary.noMatchingImageErrors} />
              <PairingErrorList errors={preflightSummary.noMatchingRowErrors} />
              <button
                type="button"
                className={styles.primaryButton}
                disabled={preflightSummary.matchedCount === 0}
                onClick={() => parseAttempt?.ok && void confirmAndStart(parseAttempt.result.entries)}
              >
                Proceed with {preflightSummary.matchedCount} matched
              </button>
            </div>
          )}
        </>
      )}

      {phase === "uploading" && <p className={styles.statusLine}>Uploading images…</p>}

      {(phase === "processing" || phase === "processingPaused" || phase === "complete") && (
        <div className={styles.progress}>
          <div className={styles.progressBarTrack}>
            <div
              className={styles.progressBarFill}
              style={{ width: totalCount > 0 ? `${(doneCount / totalCount) * 100}%` : "0%" }}
            />
          </div>
          <p className={styles.progressLine}>
            {doneCount} of {totalCount} done.{" "}
            {phase === "complete" ? "Batch complete." : formatEstimatedTimeRemaining(pendingCount)}
          </p>

          {doneCount > 0 && (
            <button type="button" className={styles.secondaryButton} onClick={handleDownloadResults}>
              Download Results
            </button>
          )}

          {phase === "processingPaused" && (
            <div className={styles.errorBadge} role="alert">
              <span>{generalError}</span>
              <button type="button" className={styles.primaryButton} onClick={handleResumeProcessingAfterPause}>
                Resume Processing
              </button>
            </div>
          )}

          {recentRowErrors.length > 0 && phase === "processing" && (
            <p className={styles.rowErrorNote}>
              {recentRowErrors.length} row(s) hit a temporary problem and will be retried automatically.
            </p>
          )}

          {phase === "complete" && (
            <button type="button" className={styles.secondaryButton} onClick={handleStartOver}>
              Start a different batch
            </button>
          )}

          <ul className={styles.rowList}>
            {rows.map((row) => (
              <BatchRowItem key={row.fileName} row={row} elapsedSeconds={rowElapsedSeconds[row.fileName]} />
            ))}
          </ul>
        </div>
      )}

      {phase === "lockBlocked" && (
        <div className={styles.errorBadge} role="alert">
          <p>
            This batch is currently being processed in another open tab
            {lockHolderTabId ? "." : " (or was, very recently)."} Close that tab, or wait
            for it to finish, then check again.
          </p>
          <button type="button" className={styles.primaryButton} onClick={handleResumeProcessingAfterPause}>
            Check again
          </button>
        </div>
      )}
    </section>
  );
}
